import {COLORS, PIECE} from './pieces';

const COLOR_ARRANGEMENT = [COLORS.BLUE, COLORS.GREEN, COLORS.WHITE, COLORS.YELLOW, COLORS.RED, COLORS.ORANGE];

export const CUBE_CENTER: PIECE = {
    colors: [COLORS.BLACK, COLORS.BLACK, COLORS.BLACK, COLORS.BLACK, COLORS.BLACK, COLORS.BLACK,
        COLORS.BLACK, COLORS.BLACK, COLORS.BLACK, COLORS.BLACK, COLORS.BLACK, COLORS.BLACK],
    position: [0, 0, 0],
};
export const RIGHT_CENTER: PIECE = {
    colors: [COLOR_ARRANGEMENT[0], COLOR_ARRANGEMENT[0], COLORS.BLACK, COLORS.BLACK, COLORS.BLACK, COLORS.BLACK,
        COLORS.BLACK, COLORS.BLACK, COLORS.BLACK, COLORS.BLACK, COLORS.BLACK, COLORS.BLACK],
    position: [1, 0, 0],
};

export const LEFT_CENTER: PIECE = {
    colors: [COLORS.BLACK, COLORS.BLACK, COLOR_ARRANGEMENT[1], COLOR_ARRANGEMENT[1], COLORS.BLACK, COLORS.BLACK,
        COLORS.BLACK, COLORS.BLACK, COLORS.BLACK, COLORS.BLACK, COLORS.BLACK, COLORS.BLACK],
    position: [-1, 0, 0],
};

export const TOP_CENTER: PIECE = {
    colors: [COLORS.BLACK, COLORS.BLACK, COLORS.BLACK, COLORS.BLACK, COLOR_ARRANGEMENT[2], COLOR_ARRANGEMENT[2],
        COLORS.BLACK, COLORS.BLACK, COLORS.BLACK, COLORS.BLACK, COLORS.BLACK, COLORS.BLACK],
    position: [0, 1, 0],
};

export const BOTTOM_CENTER: PIECE = {
    colors: [COLORS.BLACK, COLORS.BLACK, COLORS.BLACK, COLORS.BLACK, COLORS.BLACK, COLORS.BLACK,
        COLOR_ARRANGEMENT[3], COLOR_ARRANGEMENT[3], COLORS.BLACK, COLORS.BLACK, COLORS.BLACK, COLORS.BLACK],
    position: [0, -1, 0],
};

export const FRONT_CENTER: PIECE = {
    colors: [COLORS.BLACK, COLORS.BLACK, COLORS.BLACK, COLORS.BLACK, COLORS.BLACK, COLORS.BLACK,
        COLORS.BLACK, COLORS.BLACK, COLOR_ARRANGEMENT[4], COLOR_ARRANGEMENT[4], COLORS.BLACK, COLORS.BLACK],
    position: [0, 0, 1],
};

export const REAR_CENTER: PIECE = {
    colors: [COLORS.BLACK, COLORS.BLACK, COLORS.BLACK, COLORS.BLACK, COLORS.BLACK, COLORS.BLACK,
        COLORS.BLACK, COLORS.BLACK, COLORS.BLACK, COLORS.BLACK, COLOR_ARRANGEMENT[5], COLOR_ARRANGEMENT[5]],
    position: [0, 0, -1],
};








