import {createPiece, PIECE} from './pieces';

const DIMENSION = 3;

const NUMBER_OF_PIECE_FACES = Math.pow(DIMENSION, 2) * 6;

const COLORS = {
    BLUE: 0x0000FF,
    GREEN: 0x0FF000,
    WHITE: 0xFFFFFF,
    YELLOW: 0xFFFF00,
    RED: 0xFF0000,
    ORANGE: 0xFFA500,
    BLACK: 0X00000,
};

const PIECES: PIECE[] = [
    {
        colors: [COLORS.BLACK, COLORS.BLACK, COLORS.GREEN, COLORS.GREEN, COLORS.WHITE, COLORS.WHITE,
            COLORS.BLACK, COLORS.BLACK, COLORS.RED, COLORS.RED, COLORS.BLACK, COLORS.BLACK],
        position: [-1, 1, 1],
    }, {
        colors: [COLORS.BLACK, COLORS.BLACK, COLORS.BLACK, COLORS.BLACK, COLORS.WHITE, COLORS.WHITE,
            COLORS.BLACK, COLORS.BLACK, COLORS.RED, COLORS.RED, COLORS.BLACK, COLORS.BLACK],
        position: [0, 1, 1],
    }, {
        colors: [COLORS.BLUE, COLORS.BLUE, COLORS.BLACK, COLORS.BLACK, COLORS.WHITE, COLORS.WHITE,
            COLORS.BLACK, COLORS.BLACK, COLORS.RED, COLORS.RED, COLORS.BLACK, COLORS.BLACK],
        position: [1, 1, 1],
    }, {
        colors: [COLORS.BLACK, COLORS.BLACK, COLORS.GREEN, COLORS.GREEN, COLORS.BLACK, COLORS.BLACK,
            COLORS.BLACK, COLORS.BLACK, COLORS.RED, COLORS.RED, COLORS.BLACK, COLORS.BLACK],
        position: [-1, 0, 1],
    }, {
        colors: [COLORS.BLACK, COLORS.BLACK, COLORS.BLACK, COLORS.BLACK, COLORS.BLACK, COLORS.BLACK,
            COLORS.BLACK, COLORS.BLACK, COLORS.RED, COLORS.RED, COLORS.BLACK, COLORS.BLACK],
        position: [0, 0, 1],
    }, {
        colors: [COLORS.BLUE, COLORS.BLUE, COLORS.BLACK, COLORS.BLACK, COLORS.BLACK, COLORS.BLACK,
            COLORS.BLACK, COLORS.BLACK, COLORS.RED, COLORS.RED, COLORS.BLACK, COLORS.BLACK],
        position: [1, 0, 1],
    }, {
        colors: [COLORS.BLACK, COLORS.BLACK, COLORS.GREEN, COLORS.GREEN, COLORS.BLACK, COLORS.BLACK,
            COLORS.YELLOW, COLORS.YELLOW, COLORS.RED, COLORS.RED, COLORS.BLACK, COLORS.BLACK],
        position: [-1, -1, 1],
    }, {
        colors: [COLORS.BLACK, COLORS.BLACK, COLORS.BLACK, COLORS.BLACK, COLORS.BLACK, COLORS.BLACK,
            COLORS.YELLOW, COLORS.YELLOW, COLORS.RED, COLORS.RED, COLORS.BLACK, COLORS.BLACK],
        position: [0, -1, 1],
    }, {
        colors: [COLORS.BLUE, COLORS.BLUE, COLORS.BLACK, COLORS.BLACK, COLORS.BLACK, COLORS.BLACK,
            COLORS.YELLOW, COLORS.YELLOW, COLORS.RED, COLORS.RED, COLORS.BLACK, COLORS.BLACK],
        position: [1, -1, 1],
    }, {
        colors: [COLORS.BLACK, COLORS.BLACK, COLORS.GREEN, COLORS.GREEN, COLORS.WHITE, COLORS.WHITE,
            COLORS.BLACK, COLORS.BLACK, COLORS.BLACK, COLORS.BLACK, COLORS.BLACK, COLORS.BLACK],
        position: [-1, 1, 0],
    }, {
        colors: [COLORS.BLACK, COLORS.BLACK, COLORS.BLACK, COLORS.BLACK, COLORS.WHITE, COLORS.WHITE,
            COLORS.BLACK, COLORS.BLACK, COLORS.BLACK, COLORS.BLACK, COLORS.BLACK, COLORS.BLACK],
        position: [0, 1, 0],
    }, {
        colors: [COLORS.BLUE, COLORS.BLUE, COLORS.BLACK, COLORS.BLACK, COLORS.WHITE, COLORS.WHITE,
            COLORS.BLACK, COLORS.BLACK, COLORS.BLACK, COLORS.BLACK, COLORS.BLACK, COLORS.BLACK],
        position: [1, 1, 0],
    }, {
        colors: [COLORS.BLACK, COLORS.BLACK, COLORS.GREEN, COLORS.GREEN, COLORS.BLACK, COLORS.BLACK,
            COLORS.BLACK, COLORS.BLACK, COLORS.BLACK, COLORS.BLACK, COLORS.BLACK, COLORS.BLACK],
        position: [-1, 0, 0],
    }, {
        colors: [COLORS.BLACK, COLORS.BLACK, COLORS.BLACK, COLORS.BLACK, COLORS.BLACK, COLORS.BLACK,
            COLORS.BLACK, COLORS.BLACK, COLORS.BLACK, COLORS.BLACK, COLORS.BLACK, COLORS.BLACK],
        position: [0, 0, 0],
    }, {
        colors: [COLORS.BLUE, COLORS.BLUE, COLORS.BLACK, COLORS.BLACK, COLORS.BLACK, COLORS.BLACK,
            COLORS.BLACK, COLORS.BLACK, COLORS.BLACK, COLORS.BLACK, COLORS.BLACK, COLORS.BLACK],
        position: [1, 0, 0],
    }, {
        colors: [COLORS.BLACK, COLORS.BLACK, COLORS.GREEN, COLORS.GREEN, COLORS.BLACK, COLORS.BLACK,
            COLORS.YELLOW, COLORS.YELLOW, COLORS.BLACK, COLORS.BLACK, COLORS.BLACK, COLORS.BLACK],
        position: [-1, -1, 0],
    }, {
        colors: [COLORS.BLACK, COLORS.BLACK, COLORS.BLACK, COLORS.BLACK, COLORS.BLACK, COLORS.BLACK,
            COLORS.YELLOW, COLORS.YELLOW, COLORS.BLACK, COLORS.BLACK, COLORS.BLACK, COLORS.BLACK],
        position: [0, -1, 0],
    }, {
        colors: [COLORS.BLUE, COLORS.BLUE, COLORS.BLACK, COLORS.BLACK, COLORS.BLACK, COLORS.BLACK,
            COLORS.YELLOW, COLORS.YELLOW, COLORS.BLACK, COLORS.BLACK, COLORS.BLACK, COLORS.BLACK],
        position: [1, -1, 0],
    }, {
        colors: [COLORS.BLACK, COLORS.BLACK, COLORS.GREEN, COLORS.GREEN, COLORS.WHITE, COLORS.WHITE,
            COLORS.BLACK, COLORS.BLACK, COLORS.BLACK, COLORS.BLACK, COLORS.ORANGE, COLORS.ORANGE],
        position: [-1, 1, -1],
    }, {
        colors: [COLORS.BLACK, COLORS.BLACK, COLORS.BLACK, COLORS.BLACK, COLORS.WHITE, COLORS.WHITE,
            COLORS.BLACK, COLORS.BLACK, COLORS.BLACK, COLORS.BLACK, COLORS.ORANGE, COLORS.ORANGE],
        position: [0, 1, -1],
    }, {
        colors: [COLORS.BLUE, COLORS.BLUE, COLORS.BLACK, COLORS.BLACK, COLORS.WHITE, COLORS.WHITE,
            COLORS.BLACK, COLORS.BLACK, COLORS.BLACK, COLORS.BLACK, COLORS.ORANGE, COLORS.ORANGE],
        position: [1, 1, -1],
    }, {
        colors: [COLORS.BLACK, COLORS.BLACK, COLORS.GREEN, COLORS.GREEN, COLORS.BLACK, COLORS.BLACK,
            COLORS.BLACK, COLORS.BLACK, COLORS.BLACK, COLORS.BLACK, COLORS.ORANGE, COLORS.ORANGE],
        position: [-1, 0, -1],
    }, {
        colors: [COLORS.BLACK, COLORS.BLACK, COLORS.BLACK, COLORS.BLACK, COLORS.BLACK, COLORS.BLACK,
            COLORS.BLACK, COLORS.BLACK, COLORS.BLACK, COLORS.BLACK, COLORS.ORANGE, COLORS.ORANGE],
        position: [0, 0, -1],
    }, {
        colors: [COLORS.BLUE, COLORS.BLUE, COLORS.BLACK, COLORS.BLACK, COLORS.BLACK, COLORS.BLACK,
            COLORS.BLACK, COLORS.BLACK, COLORS.BLACK, COLORS.BLACK, COLORS.ORANGE, COLORS.ORANGE],
        position: [1, 0, -1],
    }, {
        colors: [COLORS.BLACK, COLORS.BLACK, COLORS.GREEN, COLORS.GREEN, COLORS.BLACK, COLORS.BLACK,
            COLORS.YELLOW, COLORS.YELLOW, COLORS.BLACK, COLORS.BLACK, COLORS.ORANGE, COLORS.ORANGE],
        position: [-1, -1, -1],
    }, {
        colors: [COLORS.BLACK, COLORS.BLACK, COLORS.BLACK, COLORS.BLACK, COLORS.BLACK, COLORS.BLACK,
            COLORS.YELLOW, COLORS.YELLOW, COLORS.BLACK, COLORS.BLACK, COLORS.ORANGE, COLORS.ORANGE],
        position: [0, -1, -1],
    }, {
        colors: [COLORS.BLUE, COLORS.BLUE, COLORS.BLACK, COLORS.BLACK, COLORS.BLACK, COLORS.BLACK,
            COLORS.YELLOW, COLORS.YELLOW, COLORS.BLACK, COLORS.BLACK, COLORS.ORANGE, COLORS.ORANGE],
        position: [1, -1, -1],
    }
];


const CUBE = {
    DIMENSION,
    NUMBER_OF_PIECE_FACES,
    COLORS,
    PIECES,
};


export const createCube = () => CUBE.PIECES.map(createPiece);









